--
-- File generated with SQLiteStudio v3.3.2 on qua abr 3 08:51:15 2024
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: TAB_NOTIFICACAO
CREATE TABLE TAB_NOTIFICACAO (COD_NOTIFICACAO INTEGER PRIMARY KEY, DATA DATETIME, TITULO VARCHAR (100), IND_LIDO CHAR (1), IND_DESTAQUE CHAR (1));
INSERT INTO TAB_NOTIFICACAO (COD_NOTIFICACAO, DATA, TITULO, IND_LIDO, IND_DESTAQUE) VALUES (1, '01/01/2024', 'Alertas', 'N', 'N');

-- Table: TAB_TAREFA
CREATE TABLE TAB_TAREFA (COD_TAREFA INTEGER PRIMARY KEY NOT NULL, DESCRICAO VARCHAR (100), CATEGORIA VARCHAR (50), STATUS VARCHAR (50), DATA DATE, HORA VARCHAR (5), PAGINA INTEGER);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
